orbs:
  aws-ecr: circleci/aws-ecr@1.0.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: BUILD_AWS_ECR_ACCOUNT_URL
          context: 10kgDevTest
          create-repo: true
          region: BUILD_AWS_REGION
          repo: cicd/aws-base
          tag: "${CIRCLE_SHA1}"
